---

- name: Centreon-Web
  hosts: centreon-web
  remote_user: root

  roles:
    - "lgcosta.centreon_ansible/roles/common"
    - role: "lgcosta.centreon_ansible/roles/mariadb-server"
      mysql_password: "p4ssw0rd"
    - role: "lgcosta.centreon_ansible/roles/centreon-web"
      php_timezone: "Europe/Paris"

- name: Centreon-Poller
  hosts: centreon-poller
  remote_user: root

  roles:
    - "lgcosta.centreon_ansible/roles/common"
    - "lgcosta.centreon_ansible/roles/centreon-poller"
