---

- name: Centreon-Web
  hosts: centreon-web
  remote_user: root

  roles:
    - "roles/common"
    - role: "roles/mariadb-server"
      mysql_root_password: "p4ssw0rd"

    - role: "roles/centreon-web"
      php_timezone: "Europe/Paris"
      mysql_hostname: "localhost"
      mysql_port: "3306"
      mysql_root_password: "p4ssw0rd"
      mysql_centreon_db: "centreon"
      mysql_centstorage_db: "centreon_storage"
      mysql_centreon_username: "centreon"
      mysql_centreon_password: "p4ssw0rd"
      centreon_admin_password: "p4ssw0rd"
      plugin_pack:
        - "base-generic"
        - "Linux SNMP"

    - role: "roles/centreon-config"
      host_list:
        - {
          'host': 'test01',
          'alias': 'Server teste 01',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'state': 'enabled' # enabled, disabled, absent
        }
        - {
          'host': 'test02',
          'alias': 'Server teste 02',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'notes': 'Test notes',
          'snmp_community': 'public',
          'snmp_version': '1',
          'state': 'enabled' # enabled, disabled, absent
        }
        - {
          'host': 'test03',
          'alias': 'Server teste 03',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'state': 'absent' # enabled, disabled, absent
        }

- name: Centreon-Poller
  hosts: centreon-poller
  remote_user: root

  roles:
    - "roles/common"
    - "roles/centreon-poller"
