---

- name: Add monitor to Centreon
  hosts: webserver
  remote_user: root

  roles:
  - role: "roles/centreon-config"
    centreon_admin_password: "p4ssw0rd"
    centreon_webapi_host: "http://192.168.150.10"
    centreon_webapi_port: "80"
    configuration:
        cg:
        - {
          'name': 'testers',
          'alias': 'Testers contacts'
          }
        contacts:
        - {
          'name': 'Test contact One',
          'alias': 'test01',
          'email': 'test01@test.centreon.com',
          'password': 'easypass',
          'admin': '0',
          'gui': '1',
          'language': 'en_US',
          'auth': 'local',
          'state': 'enabled' # enabled, disabled, absent
          }
        host:
        - {
          'name': 'test01',
          'alias': 'Server teste 01',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'state': 'enabled' # enabled, disabled, absent
        }
        - {
          'name': 'test02',
          'alias': 'Server teste 02',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'notes': 'Test notes',
          'snmp_community': 'public',
          'snmp_version': '1',
          'state': 'enabled' # enabled, disabled, absent
        }
        - {
          'name': 'test03',
          'alias': 'Server teste 03',
          'address': '127.0.0.1',
          'template': 'generic-active-host-custom',
          'instance': 'central',
          'hostgroup': '',
          'state': 'absent' # enabled, disabled, absent
        }
        service:
        - {
          'host name': 'test01',
          'description': 'cpu_snmp',
          'template': '',
          'state': 'enabled' # enabled, disabled, absent
          }
