---
  - name: add epel-release repository
    yum:
      name: epel-release
      state: present

  - name: install requirements
    yum:
      name:
        - python34-requests
        - python34-PyYAML
      state: latest

  - name: Make wrapper file using template
    template:
      src: templates/wrapper.py.j2
      dest: /tmp/wrapper.py
      mode: 0755

  - name: Make config yaml file using template
    template:
      src: templates/config.yml.j2
      dest: /tmp/config.yml
      mode: 0644

  - name: Apply configuration using wrapper
    shell: /usr/bin/python3 /tmp/wrapper.py
    register: wrapperoutput
