---
  - name: install SCL package required by PHP 7.1
    yum:
      name:
        - centos-release-scl
      state: latest

  - name: install centreon web and requirements
    yum:
      name:
        - centreon-base-config-centreon-engine
        - centreon
      state: latest

  - name: Set PHP timezone configuration
    blockinfile:
      create: yes
      marker: "; {mark} ANSIBLE MANAGED BLOCK"
      path: /etc/opt/rh/rh-php71/php.d/php-timezone.ini
      content: |
        date.timezone = {{ php_timezone }}

  - name: Check PHP 7.1 FPM service
    service: name=rh-php71-php-fpm enabled=yes state=started

  - name: Check httpd service
    service: name=httpd enabled=yes state=started

  - name: 'Create Centreon user home directory'
    file:
      path: '/var/spool/centreon'
      state: 'directory'
      owner: 'centreon'
      group: 'centreon'

  - name: Generate SSH keys
    shell: ssh-keygen -t rsa -f /var/spool/centreon/.ssh/id_rsa -q -N ""
    args:
      creates: /var/spool/centreon/.ssh/id_rsa
    become: yes
    become_user: centreon

  - name: Grab public ssh to a variable
    shell: cat /var/spool/centreon/.ssh/id_rsa.pub
    register: ssh_centreonweb_key
  - set_fact: centreonweb_rsa="{{ ssh_centreonweb_key.stdout }}"

  - name: Add right in SNMP
    shell: |
      sed -i \
        -e "/^view.*\.1\.3\.6\.1\.2\.1\.1$/i\
        view centreon included .1.3.6.1" \
        -e "/^access.*$/i\
        access notConfigGroup \"\" any noauth exact centreon none none" \
        /etc/snmp/snmpd.conf

  - name: Check snmpd service
    service: name=snmpd enabled=yes state=started

  - name: Add Centreon PHP config file
    template:
      src: templates/centreon.conf.php.j2
      dest: /etc/centreon/centreon.conf.php
      owner: centreon
      group: centreon
      mode: 0644

  - name: Add Centreon Perl config file
    template:
      src: templates/conf.pm.j2
      dest: /etc/centreon/conf.pm
      owner: centreon
      group: centreon
      mode: 0644

  - stat: path=/etc/centreon/ansible_install
    register: controller_file

  - import_tasks: do_config.yml
    when: not controller_file.stat.exists and controller_file.stat.exists is defined

  - name: centcore service
    service: name=centcore enabled=yes state=started
  - name: centengine service
    service: name=centengine enabled=yes state=started
  - name: cbd service
    service: name=cbd enabled=yes state=started
  - name: Enable firewalld
    service: name=firewalld state=started enabled=yes
    when: ansible_distribution_major_version == "7"

  - name: Firewall allow http (centos7)
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
    when: ansible_distribution_major_version == "7"

  - name: Firewall allow broker (centos7)
    firewalld:
      port: 5669/tcp
      permanent: true
      state: enabled
      immediate: yes
    when: ansible_distribution_major_version == "7"

  - name: Copy installer Plugin Manager
    copy:
      src: files/install_modules.php
      dest: /tmp/install_modules.php
      mode: 0644

  - name: Install Plugin Manager extension
    shell: |
      /opt/rh/rh-php71/root/bin/php /tmp/install_modules.php && \
      rm -rf /tmp/install_modules.php

  - name: Python packages necessaries
    yum:
      name:
        - python-requests
        - python-lxml
      state: latest

  - name: Setup script to install plugins
    template:
      src: templates/do_install_basic_plugins.py.j2
      dest: /tmp/do_install_basic_plugins.py
      mode: 0644

  - name: Install Plugins
    shell: |
      /usr/bin/python /tmp/do_install_basic_plugins.py && \
      rm -rf /tmp/do_install_basic_plugins.py

