---

  - name: Create Mysql databases
    mysql_db:
      name: "{{ item }}"
      collation: 'utf8_general_ci'
      encoding: 'utf8'
      state: 'present'
      login_host: "{{ mysql_centreon_hostname }}"
      login_port: "{{ mysql_port }}"
      login_user: 'root'
      login_password: "{{ mysql_root_password }}"
    with_items:
      - "{{ mysql_centreon_db }}"
      - "{{ mysql_centstorage_db }}"

  - name: Create sql users
    mysql_user:
      name: "{{ mysql_centreon_username }}"
      login_host: "{{ mysql_centreon_hostname }}"
      login_port: "{{ mysql_port }}"
      login_user: 'root'
      login_password: "{{ mysql_root_password }}"
      host: 'localhost'
      password: "{{ mysql_centreon_password }}"
      priv: "{{ mysql_centreon_db }}.*:ALL/{{ mysql_centstorage_db }}.*:ALL"
      state: 'present'
    no_log: true


  - name: Insert SQL into centreon database
    mysql_db:
      name: "{{ mysql_centreon_db }}"
      state: 'import'
      target: "{{ item }}"
      login_host: "{{ mysql_centreon_hostname }}"
      login_port: "{{ mysql_port }}"
      login_user: 'root'
      login_password: "{{ mysql_root_password }}"
    with_items:
      - '/usr/share/centreon/www/install/createTables.sql'
      - '/usr/share/centreon/www/install/insertMacros.sql'
      - '/usr/share/centreon/www/install/var/baseconf/centreon-engine.sql'
      - '/usr/share/centreon/www/install/var/baseconf/centreon-broker.sql'
      - '/usr/share/centreon/www/install/insertTopology.sql'
      - '/usr/share/centreon/www/install/insertTimeperiods.sql'
      - '/usr/share/centreon/www/install/insertBaseConf.sql'
      - '/usr/share/centreon/www/install/insertACL.sql'

  - name: Insert SQL into centreon storage database
    mysql_db:
      name: "{{ mysql_centstorage_db }}"
      state: 'import'
      target: "{{ item }}"
      login_host: "{{ mysql_centreon_hostname }}"
      login_port: "{{ mysql_port }}"
      login_user: 'root'
      login_password: "{{ mysql_root_password }}"
    with_items:
      - '/usr/share/centreon/www/install/createTablesCentstorage.sql'
      - '/usr/share/centreon/install/missing_tables.sql'
      - '/usr/share/centreon/www/install/installBroker.sql'
