---
  php_timezone: "Europe/Paris"
  mysql_centreon_hostname: "localhost"
  mysql_centstorage_hostname: "localhost"
  mysql_port: "3306"
  mysql_root_password: "p4ssw0rd"
  mysql_centreon_username: "centreon"
  mysql_centreon_password: "p4ssw0rd"
  mysql_centreon_db: "centreon"
  mysql_centstorage_db: "centreon_storage"
  centreon_admin_password: "p4ssw0rd"

  items_replace:
    - { regexp: '(?i)@CENTREON_DIR@', replace: '/usr/share/centreon/'}
    - { regexp: '(?i)@CENTREON_ETC@', replace: '/etc/centreon/'}
    - { regexp: '(?i)@CENTREON_DIR_WWW@', replace: '/usr/share/centreon/www/'}
    - { regexp: '(?i)@CENTREON_DIR_RRD@', replace: '/var/lib/centreon'}
    - { regexp: '(?i)@CENTREON_LOG@', replace: '/var/log/centreon'}
    - { regexp: '(?i)@CENTREON_VARLIB@', replace: '/var/lib/centreon'}
    - { regexp: '(?i)@CENTREON_GROUP@', replace: 'centreon'}
    - { regexp: '(?i)@CENTREON_USER@', replace: 'centreon'}
    - { regexp: '(?i)@RRDTOOL_DIR@', replace: '/usr/bin/rrdtool'}
    - { regexp: '(?i)@APACHE_USER@', replace: 'apache'}
    - { regexp: '(?i)@APACHE_GROUP@', replace: 'apache'}
    - { regexp: '(?i)@MAILER@', replace: '/bin/mail'}
    - { regexp: '(?i)@MONITORINGENGINE_USER@', replace: 'centreon-engine'}
    - { regexp: '(?i)@MONITORINGENGINE_GROUP@', replace: 'centreon-engine'}
    - { regexp: '(?i)@MONITORINGENGINE_ETC@', replace: '/etc/centreon-engine'}
    - { regexp: '(?i)@MONITORING_ETC@', replace: '/etc/centreon-engine'}
    - { regexp: '(?i)@MONITORING_INIT_SCRIPT@', replace: 'centengine'}
    - { regexp: '(?i)@MONITORING_BINARY@', replace: '/usr/sbin/centengine'}
    - { regexp: '(?i)@MONITORING_VARLOG@', replace: '/var/log/centreon-engine'}
    - { regexp: '(?i)@MONITORING_VAR_LOG@', replace: '/var/log/centreon-engine'}
    - { regexp: '(?i)@PLUGIN_DIR@', replace: '/usr/lib/nagios/plugin'}
    - { regexp: '(?i)@NAGIOS_PLUGIN@', replace: '/usr/lib/nagios/plugin'}
    - { regexp: '(?i)@CENTREON_ENGINE_CONNECTORS@', replace: '/usr/lib64/centreon-connector'}
    - { regexp: '(?i)@CENTREON_ENGINE_LIB@', replace: '/usr/lib64/centreon-engine'}
    - { regexp: '(?i)@CENTREONBROKER_CBMOD@', replace: '/usr/lib64/nagios/cbmod.so'}
    - { regexp: '(?i)@CENTREON_PLUGINS@', replace: '/usr/lib/centreon/plugins'}
    - { regexp: '(?i)@CENTREONPLUGINS@', replace: '/usr/lib/centreon/plugins'}
    - { regexp: '(?i)@MONITORINGENGINE_PLUGIN@', replace: '/usr/lib/nagios/plugins'}
    - { regexp: '(?i)@CENTREONBROKER_CBMOD@', replace: '/usr/lib/nagios/cbmod.so'}
    - { regexp: '(?i)@MONITORING_VAR_LIB@', replace: '/var/lib/centreon-engine'}
    - { regexp: '(?i)@DB_HOST@', replace: '{{ mysql_hostname }}'}
    - { regexp: '(?i)@ADDRESS@', replace: '{{ mysql_hostname }}'}
    - { regexp: '(?i)@DB_PORT@', replace: '{{ mysql_port }}'}
    - { regexp: '(?i)@PORT@', replace: '{{ mysql_port }}'}
    - { regexp: '(?i)@DB_USER@', replace: '{{ mysql_centreon_username }}'}
    - { regexp: '(?i)@DB_PASS@', replace: '{{ mysql_centreon_password }}'}
    - { regexp: '(?i)@DB_PASSWORD@', replace: '{{ mysql_centreon_password }}'}
    - { regexp: '(?i)@UTILS_DB@', replace: 'centreon_status'}
    - { regexp: '(?i)@NDOMOD_BINARY@', replace: '/usr/lib64/nagios/ndomod.o'}
    - { regexp: '(?i)@CENTREON_ENGINE_STATS_BINARY@', replace: '/usr/sbin/centenginestats'}
    - { regexp: '(?i)@NAGIOS_BINARY@', replace: '/usr/sbin/nagios'}
    - { regexp: '(?i)@NAGIOSTATS_BINARY@', replace: '/usr/bin/nagiostat'}
    - { regexp: '(?i)@NAGIOS_INIT_SCRIPT@', replace: '/etc/init.d/nagios'}
    - { regexp: '(?i)@DB_STORAGE@', replace: 'centreon_storage'}
    - { regexp: '(?i)@STORAGE_DB@', replace: 'centreon_storage'}
    - { regexp: '(?i)@CENTREON_ENGINE_LIB@', replace: '/usr/lib64/centreon-engine'}
    - { regexp: '(?i)@CENTREONBROKER_LIB@', replace: '/usr/share/centreon/lib/centreon-broker'}
    - { regexp: '(?i)@BROKER_USER@', replace: 'centreon-broker'}
    - { regexp: '(?i)@BROKER_GROUP@', replace: 'centreon-broker'}
    - { regexp: '(?i)@CENTREONBROKER_ETC@', replace: '/etc/centreon-broker'}
    - { regexp: '(?i)@BROKER_INIT_SCRIPT@', replace: 'cbd'}
    - { regexp: '(?i)@CENTREONBROKER_LOG@', replace: '/var/log/centreon-broker'}
    - { regexp: '(?i)@CENTREONBROKER_VARLIB@', replace: '/var/lib/centreon-broker'}
