---
  - name: Exit if not is a CentOS
    fail: msg="Compatible only with CentOS version 7"
    when: ansible_distribution != "CentOS" and ansible_distribution_major_version == "7"

  - stat: path=/etc/selinux/config
    register: selinux_config

  - name: add package necessary to manage selinux (if enabled)
    yum:
      name: libselinux-python
      state: present
    when: selinux_config.stat.exists == True
  - name: disable selinux (default)
    selinux:
      state: disabled
    when: selinux_config.stat.exists == True

  - name: add repo centreon centos7
    copy:
      src: files/centreon.repo
      dest: /etc/yum.repos.d/centreon.repo
      mode: 0644

  - name: add rpm key to centreon repository (CentOS7)
    rpm_key:
      state: present
      key: http://yum.centreon.com/standard/3.4/el7/stable/RPM-GPG-KEY-CES
