---
  - name: Exit if not is a CentOS
    fail: msg="Compatible only with CentOS version 7"
    when: ansible_distribution != "CentOS" and ansible_distribution_major_version == "7"

  - stat: path=/etc/selinux/config
    register: selinux_config

  - name: add package necessary to manage selinux (if enabled)
    yum:
      name: libselinux-python
      state: present
    when: selinux_config.stat.exists == True
  - name: disable selinux (default)
    selinux:
      state: disabled
    when: selinux_config.stat.exists == True

  - name: add rpm repository
    yum:
      name: http://yum.centreon.com/standard/18.10/el7/stable/noarch/RPMS/centreon-release-18.10-2.el7.centos.noarch.rpm
      state: present
