---
  - name: reload systemctl
    shell: systemctl daemon-reload
    listen: "reload systemctl daemons"
    
  - name: restart httpd
    service: name=httpd state=restarted
    listen: "restart httpd"
