host:
    - {
      'name': 'test01',
      'alias': 'Server teste 01',
      'address': '127.0.0.1',
      'template': 'generic-active-host-custom',
      'instance': 'central',
      'hostgroup': '',
      'notes': 'only test',
      'state': 'disabled' # enabled, disabled, absent
    }
    - {
      'name': 'test02',
      'alias': 'Server teste 02',
      'address': '127.0.0.1',
      'template': 'generic-active-host-custom',
      'instance': 'central',
      'hostgroup': '',
      'snmp_community': 'public',
      'snmp_version': '1',
      'state': 'enabled' # enabled, disabled, absent
    }
service:
    - {
        'description': 'port_80',
        'host name': 'test02',
        'template': 'generic-active-service',
        'check_command': 'check_centreon_dummy',
        'notes': 'other example of notes',
        'state': 'disabled' # enabled, disabled, absent
    }
